find_path(BASEENCODE_INCLUDE_DIR baseencode.h)

find_library(BASEENCODE_LIBRARIES baseencode)

mark_as_advanced(BASEENCODE_LIBRARIES BASEENCODE_INCLUDE_DIR)

if(BASEENCODE_INCLUDE_DIR AND EXISTS "${BASEENCODE_INCLUDE_DIR}/baseencode.h")
    file(STRINGS "${BASEENCODE_INCLUDE_DIR}/baseencode.h" BASEENCODE_H REGEX "^#define BASEENCODE_VERSION \"[^\"]*\"$")
    string(REGEX REPLACE "^.*BASEENCODE_VERSION \"([0-9]+).*$" "\\1" BASEENCODE_VERSION_MAJOR "${BASEENCODE_H}")
    string(REGEX REPLACE "^.*BASEENCODE_VERSION \"[0-9]+\\.([0-9]+).*$" "\\1" BASEENCODE_VERSION_MINOR  "${BASEENCODE_H}")
    string(REGEX REPLACE "^.*BASEENCODE_VERSION \"[0-9]+\\.[0-9]+\\.([0-9]+).*$" "\\1" BASEENCODE_VERSION_PATCH "${BASEENCODE_H}")
    set(BASEENCODE_VERSION_STRING "${BASEENCODE_VERSION_MAJOR}.${BASEENCODE_VERSION_MINOR}.${BASEENCODE_VERSION_PATCH}")
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Baseencode DEFAULT_MSG BASEENCODE_LIBRARIES BASEENCODE_INCLUDE_DIR)
