find_path(LIBZIP_INCLUDE_DIR zip.h)

find_library(LIBZIP_LIBRARIES zip)

mark_as_advanced(LIBZIP_LIBRARIES LIBZIP_INCLUDE_DIR)

if(LIBZIP_INCLUDE_DIR AND EXISTS "${LIBZIP_INCLUDE_DIR}/zip.h")
    file(STRINGS "${LIBZIP_INCLUDE_DIR}/zip.h" LIBZIP_H REGEX "^#define LIBZIP_VERSION \"[^\"]*\"$")
    string(REGEX REPLACE "^.*LIBZIP_VERSION \"([0-9]+).*$" "\\1" LIBZIP_VERSION_MAJOR "${LIBZIP_H}")
    string(REGEX REPLACE "^.*LIBZIP_VERSION \"[0-9]+\\.([0-9]+).*$" "\\1" LIBZIP_VERSION_MINOR  "${LIBZIP_H}")
    string(REGEX REPLACE "^.*LIBZIP_VERSION \"[0-9]+\\.[0-9]+\\.([0-9]+).*$" "\\1" LIBZIP_VERSION_PATCH "${LIBZIP_H}")
    set(LIBZIP_VERSION_STRING "${LIBZIP_VERSION_MAJOR}.${LIBZIP_VERSION_MINOR}.${LIBZIP_VERSION_PATCH}")
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Libzip DEFAULT_MSG LIBZIP_LIBRARIES LIBZIP_INCLUDE_DIR)
