find_path(LIBPNG_INCLUDE_DIR png.h)

find_library(LIBPNG_LIBRARIES png)

mark_as_advanced(LIBPNG_LIBRARIES LIBPNG_INCLUDE_DIR)

if(LIBPNG_INCLUDE_DIR AND EXISTS "${LIBPNG_INCLUDE_DIR}/png.h")
    file(STRINGS "${LIBPNG_INCLUDE_DIR}/zip.h" LIBPNG_H REGEX "^#define LIBPNG_VERSION \"[^\"]*\"$")
    string(REGEX REPLACE "^.*LIBPNG_VERSION \"([0-9]+).*$" "\\1" LIBPNG_VERSION_MAJOR "${LIBPNG_H}")
    string(REGEX REPLACE "^.*LIBPNG_VERSION \"[0-9]+\\.([0-9]+).*$" "\\1" LIBPNG_VERSION_MINOR  "${LIBPNG_H}")
    string(REGEX REPLACE "^.*LIBPNG_VERSION \"[0-9]+\\.[0-9]+\\.([0-9]+).*$" "\\1" LIBPNG_VERSION_PATCH "${LIBPNG_H}")
    set(LIBPNG_VERSION_STRING "${LIBPNG_VERSION_MAJOR}.${LIBPNG_VERSION_MINOR}.${LIBPNG_VERSION_PATCH}")
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Libpng DEFAULT_MSG LIBPNG_LIBRARIES LIBPNG_INCLUDE_DIR)
