name: "Build Debian Package"

on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: create sample script
      run: |
        mkdir -p .debpkg/usr/bin
        mkdir -p .debpkg/usr/lib/samplescript
        echo -e "echo sample" > .debpkg/usr/bin/samplescript
        chmod +x .debpkg/usr/bin/samplescript
        echo -e "a=1" > .debpkg/usr/lib/samplescript/samplescript.conf
        
    - name: build deb file
      uses: jiro4989/build-deb-action@v2
      with:
        package: samplescript
        package_root: .debpkg
        maintainer: your_name
        version: ${{ github.ref }}
        arch: 'amd64'
        depends: 'libc6 (>= 2.2.1), libpng-dev, libzip-dev, libgcrypt20-dev, libjansson-dev, libgtk-3-dev, libzbar-dev'
        desc: 'this is sample package.'
